Repository Jungle08-Week12to13-Team04/pintos_lab_docker, pull requests merged in 2025-06, with the labels that each got.

#16 fork 문제 일부 해결
  pintos-kaist/include/vm/file.h
  pintos-kaist/userprog/process.c
  pintos-kaist/vm/anon.c
  pintos-kaist/vm/file.c
  pintos-kaist/vm/vm.c
Labels: 기능 구현, 버그 해결

#19 Merge#4
  pintos-kaist/filesys/file.c
  pintos-kaist/userprog/process.c
  pintos-kaist/userprog/syscall.c
  pintos-kaist/vm/vm.c
Labels: 기능 구현, 버그 해결, 코드 수정

#30 swap 테스트 모두 통과
  pintos-kaist/include/userprog/process.h
  pintos-kaist/include/vm/vm.h
  pintos-kaist/userprog/process.c
  pintos-kaist/userprog/syscall.c
  pintos-kaist/vm/anon.c
  pintos-kaist/vm/file.c
  pintos-kaist/vm/vm.c
Labels: 버그 해결, 코드 수정

#32 mmap done. 4 failed
  .vscode/settings.json
  pintos-kaist/include/userprog/syscall.h
  pintos-kaist/userprog/process.c
  pintos-kaist/userprog/syscall.c
  pintos-kaist/vm/file.c
Labels: 버그 해결, 코드 수정
